package deploy.control

import deploy.entity.DeploySpec

/** Renders a multi-stage Dockerfile that assembles the llm4zio gateway fat-JAR in a builder stage and copies the
  * workspace into a slim JRE runtime. Kept pure so the output is easy to snapshot-test.
  */
object DockerfileRenderer:

  def render(spec: DeploySpec): String =
    s"""|# syntax=docker/dockerfile:1
        |# Generated by llm4zio-cli deploy --target docker
        |
        |FROM eclipse-temurin:21-jdk AS builder
        |WORKDIR /build
        |COPY . .
        |RUN --mount=type=cache,target=/root/.sbt \\
        |    --mount=type=cache,target=/root/.ivy2 \\
        |    --mount=type=cache,target=/root/.cache/coursier \\
        |    ./sbtx assembly || sbt assembly
        |
        |FROM eclipse-temurin:21-jre
        |WORKDIR /app
        |
        |# Gateway binary
        |COPY --from=builder /build/target/scala-*/llm4zio-*.jar /app/llm4zio.jar
        |
        |# Workspace contents (agents, evals, governance policy, board state)
        |COPY ${relativize(spec)} /workspace
        |ENV LLM4ZIO_WORKSPACE=/workspace
        |
        |EXPOSE 8080
        |ENTRYPOINT ["java", "-jar", "/app/llm4zio.jar"]
        |""".stripMargin

  private def relativize(spec: DeploySpec): String =
    val rel = spec.repoRoot.relativize(spec.workspace).toString
    if rel.isEmpty then "." else rel
