package demo.entity

import board.entity.IssuePriority

final case class MockIssueTemplate(
  id: String,
  title: String,
  priority: IssuePriority,
  tags: List[String],
  requiredCapabilities: List[String],
  acceptanceCriteria: List[String],
  estimate: Option[String],
  blockedBy: List[String],
  body: String,
)

object MockIssueCatalog:

  /** Sample `count` issues proportionally from all categories. */
  def sample(count: Int): List[MockIssueTemplate] =
    val clamped    = count.min(allIssues.size).max(1)
    val perCat     = categories.map { cat =>
      val ratio     = cat.issues.size.toDouble / allIssues.size
      val allocated = (ratio * clamped).round.toInt.max(1).min(cat.issues.size)
      cat.issues.take(allocated)
    }
    val flat       = perCat.flatten.take(clamped)
    // Fixup blockedBy: keep only refs that exist in the sampled set
    val sampledIds = flat.map(_.id).toSet
    flat.map(i => i.copy(blockedBy = i.blockedBy.filter(sampledIds.contains)))

  lazy val allIssues: List[MockIssueTemplate] = categories.flatMap(_.issues)

  // ── Categories ────────────────────────────────────────────────────────

  private case class IssueCategory(name: String, issues: List[MockIssueTemplate])

  private lazy val categories: List[IssueCategory] = List(
    setupCategory,
    restCategory,
    databaseCategory,
    authCategory,
    testingCategory,
    observabilityCategory,
    cicdCategory,
    documentationCategory,
  )

  // ── Setup / Bootstrap (5) ─────────────────────────────────────────────

  private val setupCategory = IssueCategory(
    "setup",
    List(
      MockIssueTemplate(
        "setup-01",
        "Initialize Spring Boot project with Maven",
        IssuePriority.High,
        List("setup"),
        List("code-generation"),
        List("mvn clean compile passes", "Application starts on 8080"),
        Some("S"),
        Nil,
        "Create Spring Boot 3.x project with Java 21, configure Maven wrapper, add core dependencies.",
      ),
      MockIssueTemplate(
        "setup-02",
        "Add Dockerfile and docker-compose",
        IssuePriority.Medium,
        List("setup", "docker"),
        List("code-generation"),
        List("docker build succeeds", "docker-compose up starts app + DB"),
        Some("S"),
        List("setup-01"),
        "Multi-stage Dockerfile with JRE runtime, docker-compose with PostgreSQL.",
      ),
      MockIssueTemplate(
        "setup-03",
        "Configure code formatting and linting",
        IssuePriority.Low,
        List("setup", "quality"),
        List("code-generation"),
        List("mvn spotless:check passes", "Checkstyle rules applied"),
        Some("XS"),
        List("setup-01"),
        "Add Spotless plugin with Google Java Style, configure Checkstyle rules.",
      ),
      MockIssueTemplate(
        "setup-04",
        "Create CLAUDE.md with project conventions",
        IssuePriority.Medium,
        List("setup", "documentation"),
        List("report-generation"),
        List("CLAUDE.md exists at project root", "Contains build commands and conventions"),
        Some("XS"),
        List("setup-01"),
        "Document project conventions, build commands, and architecture patterns in CLAUDE.md.",
      ),
      MockIssueTemplate(
        "setup-05",
        "Configure application profiles",
        IssuePriority.Medium,
        List("setup", "config"),
        List("code-generation"),
        List("Dev profile uses H2", "Prod profile uses PostgreSQL", "Test profile uses TestContainers"),
        Some("S"),
        List("setup-01"),
        "Set up application-dev.yml, application-prod.yml, and application-test.yml with appropriate configs.",
      ),
    ),
  )

  // ── REST Endpoints (20) ───────────────────────────────────────────────

  private val restCategory = IssueCategory(
    "rest",
    List(
      MockIssueTemplate(
        "rest-01",
        "Create OrderController with CRUD endpoints",
        IssuePriority.High,
        List("rest", "api"),
        List("code-generation"),
        List("GET /api/orders returns 200", "POST /api/orders creates order", "PUT /api/orders/{id} updates order"),
        Some("M"),
        List("setup-01"),
        "Implement OrderController with standard CRUD operations, proper HTTP status codes.",
      ),
      MockIssueTemplate(
        "rest-02",
        "Add request validation with Bean Validation",
        IssuePriority.High,
        List("rest", "validation"),
        List("code-generation"),
        List("Invalid requests return 400", "Validation errors include field names", "Custom validators work"),
        Some("S"),
        List("rest-01"),
        "Add @Valid annotations, custom constraint validators, and validation error response format.",
      ),
      MockIssueTemplate(
        "rest-03",
        "Implement pagination and sorting",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("page/size query params work", "Sort by multiple fields", "Response includes totalElements"),
        Some("S"),
        List("rest-01"),
        "Add Spring Data Pageable support, configure default page size, return PageResponse envelope.",
      ),
      MockIssueTemplate(
        "rest-04",
        "Add filtering and search endpoints",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("Filter by status works", "Filter by date range works", "Combined filters work"),
        Some("M"),
        List("rest-01", "db-01"),
        "Implement query filters using Spring Data Specifications, support status/date/amount filters.",
      ),
      MockIssueTemplate(
        "rest-05",
        "Create CustomerController",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("CRUD for customers works", "Customer-order relationship navigable"),
        Some("M"),
        List("rest-01"),
        "Implement CustomerController with endpoints for customer management.",
      ),
      MockIssueTemplate(
        "rest-06",
        "Add API versioning strategy",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List("V1 endpoints at /api/v1/", "Version negotiation via header", "Deprecation headers present"),
        Some("S"),
        List("rest-01"),
        "Implement URL-based API versioning with header-based version negotiation support.",
      ),
      MockIssueTemplate(
        "rest-07",
        "Implement global exception handler",
        IssuePriority.High,
        List("rest", "error-handling"),
        List("code-generation"),
        List("Validation errors return structured response", "404 returns proper body", "500 errors are logged"),
        Some("S"),
        List("rest-01"),
        "Create @ControllerAdvice with handlers for common exceptions, consistent error format.",
      ),
      MockIssueTemplate(
        "rest-08",
        "Add HATEOAS links to responses",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List("Responses include self links", "Collection responses include navigation links"),
        Some("S"),
        List("rest-01"),
        "Add Spring HATEOAS, implement EntityModel and CollectionModel wrappers.",
      ),
      MockIssueTemplate(
        "rest-09",
        "Create ProductController for catalog",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("CRUD for products", "Category filtering works", "Price range search works"),
        Some("M"),
        List("rest-01"),
        "Implement product catalog endpoints with category and price filtering.",
      ),
      MockIssueTemplate(
        "rest-10",
        "Add batch operations endpoint",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List(
          "POST /api/orders/batch creates multiple",
          "Partial success returns 207",
          "Transaction rollback on failure",
        ),
        Some("M"),
        List("rest-01", "db-01"),
        "Implement batch create/update endpoints with partial success handling.",
      ),
      MockIssueTemplate(
        "rest-11",
        "Implement file upload endpoint",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List("Multipart upload works", "File size limit enforced", "Supported formats validated"),
        Some("S"),
        List("rest-01"),
        "Add file upload controller for document attachments with validation.",
      ),
      MockIssueTemplate(
        "rest-12",
        "Add request/response logging interceptor",
        IssuePriority.Medium,
        List("rest", "observability"),
        List("code-generation"),
        List("Requests logged at DEBUG", "Response status logged", "Sensitive fields masked"),
        Some("S"),
        List("rest-01"),
        "Create HandlerInterceptor for structured request/response logging.",
      ),
      MockIssueTemplate(
        "rest-13",
        "Implement webhook notification endpoint",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("POST /api/webhooks registers callback", "Events delivered to registered URLs", "Retry on failure"),
        Some("M"),
        List("rest-01"),
        "Create webhook registration and delivery system for order status changes.",
      ),
      MockIssueTemplate(
        "rest-14",
        "Add content negotiation support",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List("JSON response by default", "XML response with Accept header", "CSV export for lists"),
        Some("S"),
        List("rest-01"),
        "Configure content negotiation for JSON/XML/CSV response formats.",
      ),
      MockIssueTemplate(
        "rest-15",
        "Create InventoryController",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("GET /api/inventory returns stock levels", "PUT /api/inventory/{id} adjusts stock", "Low stock alerts"),
        Some("M"),
        List("rest-01", "db-01"),
        "Implement inventory management endpoints with stock adjustment and alerting.",
      ),
      MockIssueTemplate(
        "rest-16",
        "Add ETags and conditional requests",
        IssuePriority.Low,
        List("rest", "performance"),
        List("code-generation"),
        List("ETag header in responses", "If-None-Match returns 304", "If-Match prevents conflicts"),
        Some("S"),
        List("rest-01"),
        "Implement ETag-based caching and optimistic concurrency with conditional headers.",
      ),
      MockIssueTemplate(
        "rest-17",
        "Implement async processing endpoint",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("POST returns 202 Accepted", "GET /status/{id} tracks progress", "Completion callback sent"),
        Some("M"),
        List("rest-01"),
        "Add async request processing with status tracking for long-running operations.",
      ),
      MockIssueTemplate(
        "rest-18",
        "Create ShippingController",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("Calculate shipping rates", "Track shipment status", "Address validation"),
        Some("M"),
        List("rest-01"),
        "Implement shipping rate calculation and shipment tracking endpoints.",
      ),
      MockIssueTemplate(
        "rest-19",
        "Add GraphQL endpoint",
        IssuePriority.Low,
        List("rest", "api"),
        List("code-generation"),
        List("GraphQL schema defined", "Query orders/customers works", "Mutations for CRUD"),
        Some("L"),
        List("rest-01", "db-01"),
        "Add Spring for GraphQL, define schema, implement data fetchers.",
      ),
      MockIssueTemplate(
        "rest-20",
        "Implement SSE endpoint for real-time updates",
        IssuePriority.Medium,
        List("rest", "api"),
        List("code-generation"),
        List("GET /api/events/stream returns SSE", "Order status changes emitted", "Client reconnection works"),
        Some("M"),
        List("rest-01"),
        "Create Server-Sent Events endpoint for real-time order status notifications.",
      ),
    ),
  )

  // ── Database Layer (15) ───────────────────────────────────────────────

  private val databaseCategory = IssueCategory(
    "database",
    List(
      MockIssueTemplate(
        "db-01",
        "Create Order JPA entity and repository",
        IssuePriority.High,
        List("database", "jpa"),
        List("code-generation"),
        List("Order entity maps to orders table", "Repository CRUD works", "Flyway migration creates schema"),
        Some("M"),
        List("setup-01"),
        "Define Order JPA entity with audit fields, OrderRepository interface, Flyway V1 migration.",
      ),
      MockIssueTemplate(
        "db-02",
        "Add Customer entity with relationship",
        IssuePriority.High,
        List("database", "jpa"),
        List("code-generation"),
        List("Customer entity created", "One-to-many with Order", "Cascade operations work"),
        Some("S"),
        List("db-01"),
        "Create Customer entity with bidirectional relationship to Order, proper cascade config.",
      ),
      MockIssueTemplate(
        "db-03",
        "Implement audit trail with Envers",
        IssuePriority.Medium,
        List("database", "audit"),
        List("code-generation"),
        List("Entity changes tracked", "Revision history queryable", "Audit tables created"),
        Some("M"),
        List("db-01"),
        "Add Hibernate Envers for entity audit trail, configure audit tables and revision queries.",
      ),
      MockIssueTemplate(
        "db-04",
        "Configure connection pool tuning",
        IssuePriority.Medium,
        List("database", "performance"),
        List("code-generation"),
        List("HikariCP configured", "Pool metrics exposed", "Connection timeout handled"),
        Some("S"),
        List("db-01"),
        "Tune HikariCP settings for production, expose pool metrics via Actuator.",
      ),
      MockIssueTemplate(
        "db-05",
        "Add database migration scripts V2-V5",
        IssuePriority.Medium,
        List("database", "migration"),
        List("code-generation"),
        List("V2 adds indexes", "V3 adds product table", "V4 adds inventory table", "V5 adds constraints"),
        Some("M"),
        List("db-01"),
        "Create Flyway migration scripts for product and inventory tables with proper indexes.",
      ),
      MockIssueTemplate(
        "db-06",
        "Implement specification pattern for queries",
        IssuePriority.Medium,
        List("database", "patterns"),
        List("code-generation"),
        List("Dynamic queries work", "Combined filters composable", "Null params ignored"),
        Some("M"),
        List("db-01"),
        "Create JPA Specification classes for dynamic query building with composable criteria.",
      ),
      MockIssueTemplate(
        "db-07",
        "Add Product entity and repository",
        IssuePriority.Medium,
        List("database", "jpa"),
        List("code-generation"),
        List("Product entity created", "Category relationship works", "Full-text search works"),
        Some("M"),
        List("db-01"),
        "Create Product entity with category support and full-text search capability.",
      ),
      MockIssueTemplate(
        "db-08",
        "Implement soft delete pattern",
        IssuePriority.Low,
        List("database", "patterns"),
        List("code-generation"),
        List("Deleted entities hidden from queries", "deletedAt timestamp set", "Hard delete for admin"),
        Some("S"),
        List("db-01"),
        "Add soft delete support with @SQLDelete and @Where annotations.",
      ),
      MockIssueTemplate(
        "db-09",
        "Create database seed scripts",
        IssuePriority.Low,
        List("database", "testing"),
        List("code-generation"),
        List("Dev seed data loads on startup", "Seed idempotent", "Realistic test data"),
        Some("S"),
        List("db-01"),
        "Create data.sql and seed scripts for development environment with realistic sample data.",
      ),
      MockIssueTemplate(
        "db-10",
        "Add Redis caching layer",
        IssuePriority.Medium,
        List("database", "caching"),
        List("code-generation"),
        List("Cache hit rate measurable", "Cache eviction on update", "TTL configured"),
        Some("M"),
        List("db-01"),
        "Integrate Spring Cache with Redis, configure cache regions and eviction policies.",
      ),
      MockIssueTemplate(
        "db-11",
        "Implement event outbox pattern",
        IssuePriority.Medium,
        List("database", "patterns"),
        List("code-generation"),
        List("Events written transactionally", "Outbox poller publishes", "At-least-once delivery"),
        Some("L"),
        List("db-01"),
        "Create outbox table and polling publisher for reliable domain event publishing.",
      ),
      MockIssueTemplate(
        "db-12",
        "Add multi-tenant support",
        IssuePriority.Low,
        List("database", "architecture"),
        List("code-generation"),
        List("Tenant isolation enforced", "Schema-per-tenant works", "Tenant context propagated"),
        Some("L"),
        List("db-01"),
        "Implement multi-tenancy with schema-per-tenant strategy and Hibernate filters.",
      ),
      MockIssueTemplate(
        "db-13",
        "Create Inventory entity",
        IssuePriority.Medium,
        List("database", "jpa"),
        List("code-generation"),
        List("Inventory tracks stock per product", "Concurrent updates safe", "Low stock threshold"),
        Some("M"),
        List("db-07"),
        "Create Inventory entity with optimistic locking for concurrent stock adjustments.",
      ),
      MockIssueTemplate(
        "db-14",
        "Add database health indicator",
        IssuePriority.Low,
        List("database", "monitoring"),
        List("code-generation"),
        List("Health check queries DB", "Connection pool status reported", "Slow query detection"),
        Some("S"),
        List("db-01"),
        "Create custom HealthIndicator that checks database connectivity and pool status.",
      ),
      MockIssueTemplate(
        "db-15",
        "Implement read replica routing",
        IssuePriority.Low,
        List("database", "performance"),
        List("code-generation"),
        List("Reads go to replica", "Writes go to primary", "Failover handled"),
        Some("L"),
        List("db-01"),
        "Configure AbstractRoutingDataSource for read/write splitting with replica support.",
      ),
    ),
  )

  // ── Auth / Security (15) ──────────────────────────────────────────────

  private val authCategory = IssueCategory(
    "auth",
    List(
      MockIssueTemplate(
        "auth-01",
        "Configure Spring Security filter chain",
        IssuePriority.High,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Public endpoints accessible", "Protected endpoints return 401", "CORS configured"),
        Some("M"),
        List("setup-01"),
        "Set up SecurityFilterChain with public/protected path patterns and CORS configuration.",
      ),
      MockIssueTemplate(
        "auth-02",
        "Implement JWT authentication",
        IssuePriority.High,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Login returns JWT token", "Token validated on requests", "Token expiry enforced"),
        Some("M"),
        List("auth-01"),
        "Create JWT token provider, authentication filter, and token validation logic.",
      ),
      MockIssueTemplate(
        "auth-03",
        "Add role-based access control",
        IssuePriority.High,
        List("security", "rbac"),
        List("code-generation", "security-analysis"),
        List("Admin role accesses all", "User role limited", "@PreAuthorize works"),
        Some("M"),
        List("auth-02"),
        "Implement RBAC with @PreAuthorize annotations, role hierarchy configuration.",
      ),
      MockIssueTemplate(
        "auth-04",
        "Implement OAuth2 login",
        IssuePriority.Medium,
        List("security", "oauth"),
        List("code-generation", "security-analysis"),
        List("Google login works", "GitHub login works", "User profile created from OAuth"),
        Some("L"),
        List("auth-01"),
        "Add OAuth2 client configuration for Google and GitHub social login.",
      ),
      MockIssueTemplate(
        "auth-05",
        "Add API key authentication",
        IssuePriority.Medium,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("X-API-Key header validated", "Key rotation supported", "Rate limiting per key"),
        Some("M"),
        List("auth-01"),
        "Implement API key authentication filter for service-to-service communication.",
      ),
      MockIssueTemplate(
        "auth-06",
        "Implement rate limiting",
        IssuePriority.Medium,
        List("security", "performance"),
        List("code-generation"),
        List("Rate limit headers present", "429 on excess", "Per-endpoint limits"),
        Some("M"),
        List("auth-01"),
        "Add Bucket4j rate limiting with configurable per-endpoint and per-user limits.",
      ),
      MockIssueTemplate(
        "auth-07",
        "Add password hashing and validation",
        IssuePriority.High,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Passwords hashed with BCrypt", "Complexity rules enforced", "Breach check implemented"),
        Some("S"),
        List("auth-02"),
        "Configure BCrypt password encoder, add password strength validation rules.",
      ),
      MockIssueTemplate(
        "auth-08",
        "Implement refresh token flow",
        IssuePriority.Medium,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Refresh token issued with JWT", "Token rotation works", "Revocation supported"),
        Some("M"),
        List("auth-02"),
        "Add refresh token endpoint, implement token rotation and revocation.",
      ),
      MockIssueTemplate(
        "auth-09",
        "Add CSRF protection",
        IssuePriority.Medium,
        List("security"),
        List("code-generation", "security-analysis"),
        List("CSRF token in responses", "State-changing requests validated", "API endpoints exempt"),
        Some("S"),
        List("auth-01"),
        "Configure CSRF protection with cookie-based token for web clients.",
      ),
      MockIssueTemplate(
        "auth-10",
        "Implement account lockout",
        IssuePriority.Medium,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Account locks after 5 failures", "Lockout duration configurable", "Admin can unlock"),
        Some("S"),
        List("auth-02"),
        "Add account lockout mechanism with configurable threshold and duration.",
      ),
      MockIssueTemplate(
        "auth-11",
        "Add security headers",
        IssuePriority.Medium,
        List("security"),
        List("code-generation", "security-analysis"),
        List("CSP header present", "X-Frame-Options set", "HSTS enabled"),
        Some("S"),
        List("auth-01"),
        "Configure security response headers: CSP, X-Frame-Options, HSTS, X-Content-Type-Options.",
      ),
      MockIssueTemplate(
        "auth-12",
        "Implement audit logging for auth events",
        IssuePriority.Medium,
        List("security", "audit"),
        List("code-generation", "security-analysis"),
        List("Login attempts logged", "Permission denials logged", "IP addresses captured"),
        Some("M"),
        List("auth-02"),
        "Create security event listener for authentication audit trail.",
      ),
      MockIssueTemplate(
        "auth-13",
        "Add two-factor authentication",
        IssuePriority.Low,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("TOTP setup flow works", "2FA required for admin", "Recovery codes generated"),
        Some("L"),
        List("auth-02"),
        "Implement TOTP-based two-factor authentication with recovery codes.",
      ),
      MockIssueTemplate(
        "auth-14",
        "Create user management endpoints",
        IssuePriority.Medium,
        List("security", "api"),
        List("code-generation"),
        List("Admin can list users", "User self-service profile", "Role assignment works"),
        Some("M"),
        List("auth-03"),
        "Create UserController for user CRUD, profile management, and role assignment.",
      ),
      MockIssueTemplate(
        "auth-15",
        "Implement session management",
        IssuePriority.Low,
        List("security", "auth"),
        List("code-generation", "security-analysis"),
        List("Concurrent sessions limited", "Session timeout configurable", "Force logout works"),
        Some("M"),
        List("auth-01"),
        "Configure session management with concurrent session control and timeout.",
      ),
    ),
  )

  // ── Testing (15) ──────────────────────────────────────────────────────

  private val testingCategory = IssueCategory(
    "testing",
    List(
      MockIssueTemplate(
        "test-01",
        "Set up unit test framework",
        IssuePriority.High,
        List("testing", "setup"),
        List("code-generation"),
        List("JUnit 5 configured", "Mockito available", "Test reports generated"),
        Some("S"),
        List("setup-01"),
        "Configure JUnit 5 + Mockito, add test report plugins, create test base classes.",
      ),
      MockIssueTemplate(
        "test-02",
        "Write OrderService unit tests",
        IssuePriority.High,
        List("testing", "unit-test"),
        List("code-generation"),
        List("CRUD operations tested", "Edge cases covered", "Error scenarios tested"),
        Some("M"),
        List("test-01", "rest-01"),
        "Create comprehensive unit tests for OrderService with mocked dependencies.",
      ),
      MockIssueTemplate(
        "test-03",
        "Set up TestContainers integration",
        IssuePriority.High,
        List("testing", "integration"),
        List("code-generation"),
        List("PostgreSQL container starts", "Container reused across tests", "CI compatible"),
        Some("M"),
        List("test-01"),
        "Configure TestContainers with PostgreSQL, create reusable container base class.",
      ),
      MockIssueTemplate(
        "test-04",
        "Write repository integration tests",
        IssuePriority.Medium,
        List("testing", "integration"),
        List("code-generation"),
        List("CRUD operations verified", "Custom queries tested", "Pagination verified"),
        Some("M"),
        List("test-03", "db-01"),
        "Create integration tests for repositories using TestContainers PostgreSQL.",
      ),
      MockIssueTemplate(
        "test-05",
        "Write controller integration tests",
        IssuePriority.Medium,
        List("testing", "integration"),
        List("code-generation"),
        List("Endpoints return correct status", "Response body validated", "Error responses tested"),
        Some("M"),
        List("test-03", "rest-01"),
        "Create MockMvc-based integration tests for all controller endpoints.",
      ),
      MockIssueTemplate(
        "test-06",
        "Add contract tests",
        IssuePriority.Medium,
        List("testing", "contract"),
        List("code-generation"),
        List("Provider contracts verified", "Consumer pacts generated", "CI runs contract tests"),
        Some("M"),
        List("test-01", "rest-01"),
        "Implement Spring Cloud Contract tests for API contracts.",
      ),
      MockIssueTemplate(
        "test-07",
        "Write security integration tests",
        IssuePriority.Medium,
        List("testing", "security"),
        List("code-generation"),
        List("Auth flow tested end-to-end", "Permission checks verified", "Token expiry tested"),
        Some("M"),
        List("test-03", "auth-02"),
        "Create security integration tests covering authentication and authorization flows.",
      ),
      MockIssueTemplate(
        "test-08",
        "Add performance tests with Gatling",
        IssuePriority.Low,
        List("testing", "performance"),
        List("code-generation"),
        List("Load test scenario defined", "Baseline metrics captured", "CI performance gate"),
        Some("L"),
        List("test-01", "rest-01"),
        "Create Gatling performance test scenarios for critical API endpoints.",
      ),
      MockIssueTemplate(
        "test-09",
        "Write CustomerService unit tests",
        IssuePriority.Medium,
        List("testing", "unit-test"),
        List("code-generation"),
        List("CRUD tested", "Relationship handling tested", "Validation tested"),
        Some("M"),
        List("test-01", "rest-05"),
        "Create unit tests for CustomerService with edge case coverage.",
      ),
      MockIssueTemplate(
        "test-10",
        "Add mutation testing",
        IssuePriority.Low,
        List("testing", "quality"),
        List("code-generation"),
        List("PITest configured", "Mutation score > 80%", "Report generated"),
        Some("M"),
        List("test-01"),
        "Configure PITest mutation testing, set quality gate threshold.",
      ),
      MockIssueTemplate(
        "test-11",
        "Write webhook delivery tests",
        IssuePriority.Medium,
        List("testing", "integration"),
        List("code-generation"),
        List("Webhook delivery verified", "Retry logic tested", "Failure handling tested"),
        Some("M"),
        List("test-03", "rest-13"),
        "Create integration tests for webhook registration and delivery.",
      ),
      MockIssueTemplate(
        "test-12",
        "Add API documentation tests",
        IssuePriority.Low,
        List("testing", "documentation"),
        List("code-generation"),
        List("All endpoints documented", "Examples validated", "Schema matches code"),
        Some("S"),
        List("test-01", "doc-01"),
        "Create tests that verify OpenAPI documentation matches actual API behavior.",
      ),
      MockIssueTemplate(
        "test-13",
        "Write caching integration tests",
        IssuePriority.Low,
        List("testing", "integration"),
        List("code-generation"),
        List("Cache hit verified", "Cache eviction tested", "TTL behavior validated"),
        Some("M"),
        List("test-03", "db-10"),
        "Create integration tests for Redis caching with embedded Redis or TestContainers.",
      ),
      MockIssueTemplate(
        "test-14",
        "Add end-to-end smoke tests",
        IssuePriority.Medium,
        List("testing", "e2e"),
        List("code-generation"),
        List("Health check passes", "CRUD flow works", "Auth flow works"),
        Some("M"),
        List("test-03"),
        "Create E2E smoke tests that verify critical user journeys.",
      ),
      MockIssueTemplate(
        "test-15",
        "Write batch operation tests",
        IssuePriority.Low,
        List("testing", "unit-test"),
        List("code-generation"),
        List("Batch create tested", "Partial failure tested", "Rollback verified"),
        Some("M"),
        List("test-01", "rest-10"),
        "Create tests for batch operations including partial success and rollback scenarios.",
      ),
    ),
  )

  // ── Observability (10) ────────────────────────────────────────────────

  private val observabilityCategory = IssueCategory(
    "observability",
    List(
      MockIssueTemplate(
        "obs-01",
        "Configure Actuator endpoints",
        IssuePriority.High,
        List("observability", "monitoring"),
        List("code-generation"),
        List("Health endpoint returns 200", "Info endpoint populated", "Sensitive endpoints secured"),
        Some("S"),
        List("setup-01"),
        "Configure Spring Boot Actuator with health, info, metrics, and prometheus endpoints.",
      ),
      MockIssueTemplate(
        "obs-02",
        "Add Prometheus metrics exporter",
        IssuePriority.Medium,
        List("observability", "monitoring"),
        List("code-generation"),
        List("Prometheus endpoint available", "JVM metrics exported", "Custom metrics visible"),
        Some("S"),
        List("obs-01"),
        "Configure Micrometer Prometheus registry, expose /actuator/prometheus endpoint.",
      ),
      MockIssueTemplate(
        "obs-03",
        "Implement custom business metrics",
        IssuePriority.Medium,
        List("observability", "monitoring"),
        List("code-generation"),
        List("Order count metric works", "Revenue metric updated", "Error rate tracked"),
        Some("M"),
        List("obs-02"),
        "Create MeterBinder implementations for business metrics: order count, revenue, error rates.",
      ),
      MockIssueTemplate(
        "obs-04",
        "Set up structured JSON logging",
        IssuePriority.Medium,
        List("observability", "logging"),
        List("code-generation"),
        List("JSON format in production", "Correlation IDs present", "Log levels configurable"),
        Some("S"),
        List("setup-01"),
        "Configure Logback with JSON encoder, add MDC correlation ID filter.",
      ),
      MockIssueTemplate(
        "obs-05",
        "Add distributed tracing",
        IssuePriority.Medium,
        List("observability", "tracing"),
        List("code-generation"),
        List("Trace IDs in headers", "Spans for DB calls", "Jaeger/Zipkin compatible"),
        Some("M"),
        List("obs-01"),
        "Integrate Micrometer Tracing with trace propagation and span instrumentation.",
      ),
      MockIssueTemplate(
        "obs-06",
        "Create operational dashboard config",
        IssuePriority.Low,
        List("observability", "monitoring"),
        List("report-generation"),
        List("Grafana dashboard JSON created", "Key metrics displayed", "Alert thresholds defined"),
        Some("M"),
        List("obs-02"),
        "Create Grafana dashboard JSON for key application metrics and alerts.",
      ),
      MockIssueTemplate(
        "obs-07",
        "Implement slow query detection",
        IssuePriority.Medium,
        List("observability", "performance"),
        List("code-generation"),
        List("Queries > 100ms logged", "Statistics collected", "Alert on threshold"),
        Some("S"),
        List("db-01"),
        "Configure Hibernate statistics and slow query logging with threshold alerts.",
      ),
      MockIssueTemplate(
        "obs-08",
        "Add application event logging",
        IssuePriority.Low,
        List("observability", "audit"),
        List("code-generation"),
        List("Business events logged", "Event format standardized", "Searchable in logs"),
        Some("S"),
        List("obs-04"),
        "Create standardized application event logging for business operations audit trail.",
      ),
      MockIssueTemplate(
        "obs-09",
        "Implement error tracking integration",
        IssuePriority.Medium,
        List("observability", "error-tracking"),
        List("code-generation"),
        List("Exceptions captured", "Stack traces included", "Context attached"),
        Some("S"),
        List("obs-01"),
        "Integrate error tracking (Sentry-compatible) for exception monitoring with context.",
      ),
      MockIssueTemplate(
        "obs-10",
        "Add SLA monitoring",
        IssuePriority.Low,
        List("observability", "monitoring"),
        List("code-generation"),
        List("Response time percentiles tracked", "SLA breach alerts", "Availability metric"),
        Some("M"),
        List("obs-02"),
        "Create SLA monitoring with response time percentiles and availability tracking.",
      ),
    ),
  )

  // ── CI/CD (10) ────────────────────────────────────────────────────────

  private val cicdCategory = IssueCategory(
    "cicd",
    List(
      MockIssueTemplate(
        "ci-01",
        "Create GitHub Actions CI workflow",
        IssuePriority.High,
        List("devops", "ci"),
        List("code-generation"),
        List("Build runs on push", "Tests execute in CI", "Artifacts uploaded"),
        Some("M"),
        List("setup-01"),
        "Create .github/workflows/ci.yml with build, test, and artifact upload steps.",
      ),
      MockIssueTemplate(
        "ci-02",
        "Add Docker image build and push",
        IssuePriority.Medium,
        List("devops", "ci", "docker"),
        List("code-generation"),
        List("Docker build in CI", "Image tagged with version", "Pushed to registry"),
        Some("S"),
        List("ci-01", "setup-02"),
        "Add Docker build step to CI, push to GHCR with version tagging.",
      ),
      MockIssueTemplate(
        "ci-03",
        "Configure staging deployment",
        IssuePriority.Medium,
        List("devops", "cd"),
        List("code-generation"),
        List("Deploy to staging on merge", "Health check verified", "Rollback supported"),
        Some("M"),
        List("ci-01"),
        "Add staging deployment step with health check verification and rollback.",
      ),
      MockIssueTemplate(
        "ci-04",
        "Add dependency vulnerability scanning",
        IssuePriority.Medium,
        List("devops", "security"),
        List("code-generation"),
        List("OWASP scan runs", "CVE report generated", "Build fails on critical"),
        Some("S"),
        List("ci-01"),
        "Add OWASP dependency-check to CI pipeline, configure severity thresholds.",
      ),
      MockIssueTemplate(
        "ci-05",
        "Configure release automation",
        IssuePriority.Medium,
        List("devops", "release"),
        List("code-generation"),
        List("Semantic versioning applied", "Changelog generated", "GitHub release created"),
        Some("M"),
        List("ci-01"),
        "Add release workflow with semantic versioning, changelog generation, and GitHub releases.",
      ),
      MockIssueTemplate(
        "ci-06",
        "Add code coverage reporting",
        IssuePriority.Medium,
        List("devops", "testing"),
        List("code-generation"),
        List("JaCoCo reports generated", "Coverage threshold enforced", "Report published"),
        Some("S"),
        List("ci-01", "test-01"),
        "Configure JaCoCo code coverage with CI reporting and quality gate.",
      ),
      MockIssueTemplate(
        "ci-07",
        "Create environment configuration",
        IssuePriority.Medium,
        List("devops", "config"),
        List("code-generation"),
        List("Dev/staging/prod configs", "Secrets managed", "Feature flags supported"),
        Some("M"),
        List("ci-01"),
        "Set up environment-specific configuration with GitHub secrets and feature flags.",
      ),
      MockIssueTemplate(
        "ci-08",
        "Add database migration CI step",
        IssuePriority.Low,
        List("devops", "database"),
        List("code-generation"),
        List("Migrations tested in CI", "Rollback scripts verified", "Schema diff generated"),
        Some("S"),
        List("ci-01", "db-01"),
        "Add Flyway migration validation to CI pipeline with rollback verification.",
      ),
      MockIssueTemplate(
        "ci-09",
        "Configure branch protection rules",
        IssuePriority.Low,
        List("devops", "governance"),
        List("code-generation"),
        List("PR required for main", "CI must pass", "Approval required"),
        Some("XS"),
        List("ci-01"),
        "Set up branch protection rules for main branch via GitHub API.",
      ),
      MockIssueTemplate(
        "ci-10",
        "Add infrastructure-as-code",
        IssuePriority.Low,
        List("devops", "infrastructure"),
        List("code-generation"),
        List("Terraform configs created", "State managed remotely", "Plan runs in PR"),
        Some("L"),
        List("ci-01"),
        "Create Terraform configurations for cloud infrastructure with remote state.",
      ),
    ),
  )

  // ── Documentation (10) ────────────────────────────────────────────────

  private val documentationCategory = IssueCategory(
    "documentation",
    List(
      MockIssueTemplate(
        "doc-01",
        "Create OpenAPI specification",
        IssuePriority.High,
        List("documentation", "api"),
        List("report-generation"),
        List("Swagger UI accessible", "All endpoints documented", "Examples included"),
        Some("M"),
        List("rest-01"),
        "Add springdoc-openapi, annotate controllers with OpenAPI annotations.",
      ),
      MockIssueTemplate(
        "doc-02",
        "Write README with setup instructions",
        IssuePriority.Medium,
        List("documentation"),
        List("report-generation"),
        List("Quick start guide", "Prerequisites listed", "Architecture overview"),
        Some("S"),
        List("setup-01"),
        "Create comprehensive README with setup, build, run, and architecture documentation.",
      ),
      MockIssueTemplate(
        "doc-03",
        "Create architecture decision records",
        IssuePriority.Low,
        List("documentation", "architecture"),
        List("report-generation"),
        List("ADR template created", "Key decisions documented", "Trade-offs explained"),
        Some("M"),
        Nil,
        "Set up ADR directory, document key architectural decisions with context and trade-offs.",
      ),
      MockIssueTemplate(
        "doc-04",
        "Write API usage guide",
        IssuePriority.Medium,
        List("documentation", "api"),
        List("report-generation"),
        List("Authentication guide", "Common use cases covered", "Error handling explained"),
        Some("M"),
        List("doc-01"),
        "Create developer guide covering authentication, common API patterns, and error handling.",
      ),
      MockIssueTemplate(
        "doc-05",
        "Create runbook for operations",
        IssuePriority.Medium,
        List("documentation", "operations"),
        List("report-generation"),
        List("Deployment procedures", "Troubleshooting guide", "Incident response"),
        Some("M"),
        List("ci-01"),
        "Write operations runbook covering deployment, monitoring, troubleshooting, and incidents.",
      ),
      MockIssueTemplate(
        "doc-06",
        "Add data model documentation",
        IssuePriority.Low,
        List("documentation", "database"),
        List("report-generation"),
        List("ER diagram created", "Entity descriptions", "Relationship explanations"),
        Some("M"),
        List("db-01"),
        "Create data model documentation with ER diagrams and entity descriptions.",
      ),
      MockIssueTemplate(
        "doc-07",
        "Write security documentation",
        IssuePriority.Medium,
        List("documentation", "security"),
        List("report-generation"),
        List("Auth flow documented", "Security controls listed", "Compliance mapping"),
        Some("M"),
        List("auth-01"),
        "Document security architecture, authentication flows, and compliance controls.",
      ),
      MockIssueTemplate(
        "doc-08",
        "Create contributing guide",
        IssuePriority.Low,
        List("documentation"),
        List("report-generation"),
        List("Code standards documented", "PR process explained", "Development workflow"),
        Some("S"),
        Nil,
        "Write CONTRIBUTING.md with code standards, PR workflow, and development setup.",
      ),
      MockIssueTemplate(
        "doc-09",
        "Add changelog",
        IssuePriority.Low,
        List("documentation"),
        List("report-generation"),
        List("Changelog format standardized", "Breaking changes highlighted", "Version history complete"),
        Some("S"),
        Nil,
        "Create CHANGELOG.md following Keep a Changelog format.",
      ),
      MockIssueTemplate(
        "doc-10",
        "Write deployment guide",
        IssuePriority.Medium,
        List("documentation", "operations"),
        List("report-generation"),
        List("Docker deployment documented", "Cloud deployment guide", "Environment variables listed"),
        Some("M"),
        List("setup-02"),
        "Create deployment guide covering Docker, cloud, and environment configuration.",
      ),
    ),
  )
