package bankmod.app

import java.nio.file.{ Files, Path, Paths, StandardOpenOption }

import zio.*

import bankmod.graph.model.*
import bankmod.graph.render.{ JsonSchemaInterpreter, MermaidInterpreter, SampleGraph }
import bankmod.mcp.tools.{
  ExplainInvariantViolationInput,
  ExplainInvariantViolationTool,
  ListInvariantsTool,
}

/** Emits a plain-markdown doc bundle under `docs/bankmod/generated/`.
  *
  * Option-2 scope (per M7 trim): no Laika plugin, no external SVG renderer. Pages use GitHub-flavoured fenced `mermaid`
  * blocks, which render natively on github.com and on most markdown readers.
  *
  * Single source of truth:
  *   - Diagram: [[MermaidInterpreter]] on [[SampleGraph.sample]].
  *   - Invariant catalog: [[ListInvariantsTool.catalog]] + [[ExplainInvariantViolationTool.run]].
  *   - JSON Schema reference: [[JsonSchemaInterpreter.jsonSchema]] (zio-blocks-schema-derived).
  *
  * Usage: `sbt "bankmodApp/runMain bankmod.app.DocsGenerator"` — writes to the repo's `docs/bankmod/generated/`.
  */
object DocsGenerator extends ZIOAppDefault:

  /** Default output: walk up from CWD looking for the repo root (directory containing `build.sbt`) and write to
    * `<root>/docs/bankmod/generated`. This makes the tool behave identically whether invoked from the repo root or from
    * inside an sbt fork whose CWD is the module base.
    */
  private def defaultOutDir: Path =
    val cwd                     = Paths.get("").toAbsolutePath
    def findRoot(p: Path): Path =
      Option(p).fold(cwd) { path =>
        if Files.exists(path.resolve("build.sbt")) then path
        else Option(path.getParent).fold(cwd)(findRoot)
      }
    findRoot(cwd).resolve("docs").resolve("bankmod").resolve("generated")

  override def run: ZIO[ZIOAppArgs, Throwable, Unit] =
    for
      args  <- getArgs
      outDir = args.headOption.map(Paths.get(_)).getOrElse(defaultOutDir)
      _     <- ZIO.attemptBlocking(Files.createDirectories(outDir.resolve("services")))
      _     <- writeFile(outDir.resolve("index.md"), renderIndex(SampleGraph.sample))
      _     <- writeFile(outDir.resolve("invariants.md"), renderInvariants())
      _     <- writeFile(outDir.resolve("graph-schema.json"), JsonSchemaInterpreter.jsonSchema)
      _     <- ZIO.foreachDiscard(SampleGraph.sample.services.values.toList.sortBy(_.id.value)) { svc =>
                 writeFile(
                   outDir.resolve("services").resolve(s"${svc.id.value}.md"),
                   renderService(svc, SampleGraph.sample),
                 )
               }
      _     <- Console.printLine(s"bankmod docs: wrote ${SampleGraph.sample.services.size + 3} files under $outDir")
    yield ()

  private def writeFile(path: Path, body: String): ZIO[Any, Throwable, Unit] =
    ZIO
      .attemptBlocking(
        Files.writeString(
          path,
          body,
          StandardOpenOption.CREATE,
          StandardOpenOption.TRUNCATE_EXISTING,
        )
      )
      .unit

  // ── Renderers ────────────────────────────────────────────────────────────

  private def renderIndex(g: Graph): String =
    List(
      "# bankmod — Services Graph",
      "",
      "> Auto-generated by `DocsGenerator`. Do not edit by hand.",
      "",
      "The canonical 8-service fixture used for bankmod's validator, renderers, and demo scenarios.",
      "",
      "## Full graph",
      "",
      "```mermaid",
      MermaidInterpreter.interpreter.render(g),
      "```",
      "",
      "## Services by tier",
      "",
      servicesByTierTable(g),
      "## Further reading",
      "",
      "- [Invariant catalog](./invariants.md)",
      "- [JSON Schema for `Graph`](./graph-schema.json)",
      "- Per-service pages under [`./services/`](./services/)",
      "- Demo script: [../demo-script.md](../demo-script.md)",
      "",
    ).mkString("\n")

  private def servicesByTierTable(g: Graph): String =
    val byTier                       = g.services.values.toList.sortBy(_.id.value).groupBy(_.tier)
    val tierOrder: List[Criticality] = List(Criticality.Tier1, Criticality.Tier2, Criticality.Tier3)
    tierOrder.flatMap { t =>
      byTier.get(t).map { svcs =>
        val rows = svcs
          .map(s =>
            s"| [`${s.id.value}`](./services/${s.id.value}.md) | ${s.owner} | ${s.inbound.size} | ${s.outbound.size} |"
          )
          .mkString("\n")
        List(
          s"### $t",
          "",
          "| service | owner | inbound ports | outbound edges |",
          "|---|---|---|---|",
          rows,
          "",
        ).mkString("\n")
      }
    }.mkString("\n")

  private def renderService(svc: Service, g: Graph): String =
    val inboundList =
      if svc.inbound.isEmpty then "_none_"
      else svc.inbound.toList.map(p => s"- `${p.name.value}`").sorted.mkString("\n")

    val outboundList =
      if svc.outbound.isEmpty then "_none_"
      else
        svc.outbound.toList
          .sortBy(e => (e.toService.value, e.toPort.value))
          .map(e =>
            s"- `${e.fromPort.value}` → [`${e.toService.value}`](./${e.toService.value}.md) on `${e.toPort.value}`" +
              s" — ${protocolLabel(e.protocol)}, ${e.consistency}, ${e.ordering}"
          )
          .mkString("\n")

    val callers     = g.services.values
      .filter(_.outbound.exists(_.toService == svc.id))
      .toList
      .sortBy(_.id.value)
    val callersList =
      if callers.isEmpty then "_no upstream callers in the sample graph_"
      else callers.map(c => s"- [`${c.id.value}`](./${c.id.value}.md)").mkString("\n")

    List(
      s"# ${svc.id.value}",
      "",
      "> Auto-generated by `DocsGenerator`. Do not edit by hand.",
      "",
      "| property | value |",
      "|---|---|",
      s"| **tier** | ${svc.tier} |",
      s"| **owner** | ${svc.owner} |",
      s"| **latency p99** | ${svc.sla.latencyP99Ms} ms |",
      s"| **availability** | ${svc.sla.availabilityPct}% |",
      s"| **max retries** | ${svc.sla.maxRetries} |",
      "",
      "## Inbound ports",
      "",
      inboundList,
      "",
      "## Outbound edges",
      "",
      outboundList,
      "",
      "## Upstream callers",
      "",
      callersList,
      "",
    ).mkString("\n")

  private def protocolLabel(p: Protocol): String = p match
    case Protocol.Rest(url)    => s"REST → $url"
    case Protocol.Grpc(svc)    => s"gRPC → $svc"
    case Protocol.Event(topic) => s"Event → `$topic`"
    case Protocol.Graphql(url) => s"GraphQL → $url"
    case Protocol.Soap(url)    => s"SOAP → $url"

  private def renderInvariants(): String =
    val body = ListInvariantsTool.catalog
      .map { entry =>
        val explained = ExplainInvariantViolationTool.run(
          ExplainInvariantViolationInput(entry.kind, "")
        )
        val fixes     =
          if explained.fixSuggestions.isEmpty then "_no suggestions_"
          else explained.fixSuggestions.map(f => s"- $f").mkString("\n")
        s"""### ${entry.kind}
           |
           |${entry.shortDescription}
           |
           |${explained.explanation}
           |
           |**Suggested fixes:**
           |
           |$fixes
           |""".stripMargin
      }
      .mkString("\n")

    s"""# bankmod — Invariant Catalog
       |
       |> Auto-generated by `DocsGenerator`. Do not edit by hand.
       |
       |Every invariant the validator enforces. These map directly to the `kind` field on
       |`validateEvolution` error items and to the `errorKind` parameter of
       |`explainInvariantViolation`.
       |
       |$body
       |""".stripMargin
